drmemory.exe -no_results_to_stderr -- .\Win32_DLL_Dynamic_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_DLL_Dynamic_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_DLL_Static_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_DLL_Static_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_LIB_MD_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_LIB_MD_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_LIB_MT_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\Win32_LIB_MT_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_DLL_Dynamic_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_DLL_Dynamic_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_DLL_Static_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_DLL_Static_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_LIB_MD_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_LIB_MD_Release\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_LIB_MT_Debug\zlibwapitest.exe
drmemory.exe -no_results_to_stderr -- .\x64_LIB_MT_Release\zlibwapitest.exe
